"""New Squares Transfer — model-agnostic data & test-manifest generation.

Generates the games and matched test sets that BOTH the GPT and MLP runners
consume, so the two models are trained and evaluated on identical data.  No
torch / mingpt imports here on purpose — this module is pure data.

Three controls (all live here, so they apply to both models for free):

  1. Equal new-square exposure  (--new-square-legal-budget N):
     each condition's training set is grown until it contains exactly N
     positions where >=1 new square is legal.  New-square legality is
     model-independent (positions, not next-token targets), and this is a
     DATA balance — no loss reweighting.

  2. Length-matched evaluation:
     every test position is tagged with the firing rule's chain length, so
     coherent (new-row flank) and incoherent (random flank) are compared at
     equal pattern length.

  3. Matched ceiling:
     positions are also tagged with n_legal.  Games are generated by uniform-
     random play, so a converged model learns P(move) ~ 1/n_legal; matching
     n_legal across conditions makes the IL_prob learning curves share an
     asymptote.  (Matched in expectation under the uniform policy, not a hard
     guarantee.)

A literal "same board" eval is impossible (the conditions have different
rules), so (2)+(3) match on (firing_length, n_legal) buckets instead.  The
eval reports per-bucket metrics; compare like-for-like buckets across
conditions.

Outputs per condition:
  experiments/new_squares/cond_XXX/{rules.json, train_games.pickle,
                                    test_manifest.json, gen_stats.json}
"""

import argparse
import json
import os
import pickle
import time

import numpy as np

from data.othello import OthelloBoardState

# Standard Othello has 60 playable cells (0-63 minus center 4).
# New squares are cells 64-71.
CENTER_CELLS = {27, 28, 35, 36}
NEW_SQUARE_IDS = list(range(64, 72))
N_NEW = 8
RULES_PER_SQUARE = 5
# Each new square's rules split into a SHARED along-row block (flanks along the
# new row -> references other new squares; identical in both conditions) and a
# condition-specific into-board block (flanks into the pre-existing board:
# coherent = geometrically-adjacent existing cells, incoherent = random
# existing cells).  This equalizes the inter-new-square (bootstrapping)
# structure so the ONLY difference is whether the connection to the existing
# board is spatially coherent.
N_ALONG_ROW = 2
N_INTO_BOARD = RULES_PER_SQUARE - N_ALONG_ROW    # 3
N_CELLS = 72                       # 64 standard + 8 new; the cell-score space
# Condition-id -> name.  0/1 = original fixed-N_INTO_BOARD design; 2/3 = the
# "all coherent into-board relationships" variant (per-square rule count varies
# 9/12/7... but is identical between coherent_all and incoherent_all).
CONDITIONS = ['coherent', 'incoherent', 'coherent_all', 'incoherent_all']


def rule_length(rule):
    """Chain length of a flanking rule = opponents + terminal."""
    return len(rule['opponents']) + 1


# ============================================================================
# Rule generation for new squares
# ============================================================================

def _pick(candidates, n):
    """Deterministically select n rules, preferring distinct directions then
    shorter chains.  Pads by cycling if a square has too few candidates."""
    ordered = sorted(candidates, key=lambda r: (len(r['opponents']),
                                                 r['direction']))
    selected, dirs = [], set()
    for c in ordered:
        if c['direction'] not in dirs and len(selected) < n:
            selected.append(c)
            dirs.add(c['direction'])
    for c in ordered:
        if len(selected) >= n:
            break
        if c not in selected:
            selected.append(c)
    k = 0
    while len(selected) < n and ordered:
        selected.append(dict(ordered[k % len(ordered)]))
        k += 1
    return selected[:n]


def _along_row_candidates(i):
    """Flanks ALONG the new row from square 64+i -> reference OTHER new squares.
    Shared by both conditions (the internal row structure is controlled)."""
    new_cell = 64 + i
    cands = []
    chain = []                                  # rightward
    for j in range(i + 1, 8):
        chain.append(64 + j)
        if len(chain) >= 2:
            cands.append({'target': new_cell, 'opponents': list(chain[:-1]),
                          'terminal': chain[-1], 'direction': 'along_right'})
    chain = []                                  # leftward
    for j in range(i - 1, -1, -1):
        chain.append(64 + j)
        if len(chain) >= 2:
            cands.append({'target': new_cell, 'opponents': list(chain[:-1]),
                          'terminal': chain[-1], 'direction': 'along_left'})
    return cands


def _coherent_into_board_candidates(i):
    """Flanks INTO the pre-existing board from square 64+i (conceptually below
    column i): straight up + diagonals through EXISTING cells only."""
    new_cell = 64 + i
    col = i
    cands = []
    chain = []                                  # up
    for row in range(7, -1, -1):
        cell = row * 8 + col
        if cell in CENTER_CELLS:
            break
        chain.append(cell)
        if len(chain) >= 2:
            cands.append({'target': new_cell, 'opponents': list(chain[:-1]),
                          'terminal': chain[-1], 'direction': 'up'})
    chain = []; r, c = 7, col + 1               # diag up-right
    while r >= 0 and c < 8:
        cell = r * 8 + c
        if cell in CENTER_CELLS:
            break
        chain.append(cell)
        if len(chain) >= 2:
            cands.append({'target': new_cell, 'opponents': list(chain[:-1]),
                          'terminal': chain[-1], 'direction': 'diag_up_right'})
        r -= 1; c += 1
    chain = []; r, c = 7, col - 1               # diag up-left
    while r >= 0 and c >= 0:
        cell = r * 8 + c
        if cell in CENTER_CELLS:
            break
        chain.append(cell)
        if len(chain) >= 2:
            cands.append({'target': new_cell, 'opponents': list(chain[:-1]),
                          'terminal': chain[-1], 'direction': 'diag_up_left'})
        r -= 1; c -= 1
    return cands


def _along_row_pool(i, use_all):
    """Along-row (new-square -> new-square) rules for square i.  Shared block,
    identical in both conditions.  use_all=True uses EVERY along-row flank
    (count varies per square); False keeps the fixed N_ALONG_ROW selection."""
    cands = _along_row_candidates(i)
    return cands if use_all else _pick(cands, N_ALONG_ROW)


def _into_board_pool(i, use_all):
    """Coherent into-board rules for square i.  use_all=True uses EVERY
    reachable coherent flank (count varies per square: 9/12/7...); False keeps
    the fixed N_INTO_BOARD-rule selection (original design)."""
    cands = _coherent_into_board_candidates(i)
    return cands if use_all else _pick(cands, N_INTO_BOARD)


def create_coherent_rules(rng=None, use_all=False):
    """Per new square: shared along-row flanks (reference other new squares) +
    into-board flanks into the existing board via geometrically-adjacent cells.
    Deterministic.  use_all=True uses the FULL candidate pools for BOTH blocks
    (all geometric relationships; per-square count varies)."""
    rules = []
    for i in range(N_NEW):
        rules.extend(_along_row_pool(i, use_all))
        rules.extend(_into_board_pool(i, use_all))
    return rules


def create_incoherent_rules(rng, use_all=False):
    """Identical shared along-row block as coherent (same pool), but the
    into-board flanks reference RANDOM existing cells, matched to coherent's
    into-board rules ONE-FOR-ONE (same per-square count AND chain-length
    distribution).  use_all=True mirrors the full coherent pools, so the two
    conditions share the identical (unequal) per-square distribution and differ
    ONLY in coherent-geometry vs random-target on the into-board block."""
    playable = [c for c in range(64) if c not in CENTER_CELLS]
    rules = []
    for i in range(N_NEW):
        rules.extend(_along_row_pool(i, use_all))                    # identical
        for r in _into_board_pool(i, use_all):
            n_opp = max(1, rule_length(r) - 1)
            cells = rng.choice(playable, size=n_opp + 1, replace=False)
            rules.append({'target': 64 + i,
                          'opponents': cells[:-1].tolist(),
                          'terminal': int(cells[-1]),
                          'direction': 'random_into_board'})
    return rules


def make_rules(condition_name, rng):
    """Conditions: 'coherent' / 'incoherent' (fixed N_ALONG_ROW + N_INTO_BOARD
    per square), and 'coherent_all' / 'incoherent_all' (full candidate pools for
    both blocks; per-square count varies but is IDENTICAL across the two)."""
    use_all = condition_name.endswith('_all')
    base = condition_name[:-4] if use_all else condition_name
    if base == 'coherent':
        return create_coherent_rules(rng, use_all=use_all)
    return create_incoherent_rules(rng, use_all=use_all)


# ============================================================================
# Extended game engine (supports cells 64-71), uniform-random play
# ============================================================================

def generate_game_with_new_squares(new_rules, rng, save_legal=False):
    """Play one uniform-random game on the 8x8 board + 8 new squares.

    If save_legal, also return per-decision records with the info needed to
    bucket test positions: the prefix length, the full legal set, and the
    firing rule length for each legal new square.

    Returns:
      moves                          if not save_legal
      (moves, turn_records)          if save_legal
        turn_records[i] = {'prefix_len', 'all_legal', 'new_firing'}
        new_firing: {new_cell: min firing-rule length}
    """
    board = OthelloBoardState()
    new_state = np.zeros(N_NEW, dtype=np.int32)     # 0 empty, 1 black, -1 white
    moves = []
    turn_records = [] if save_legal else None

    for _turn in range(68):
        flat = board.state.flatten()
        is_black = (board.next_hand_color == 1)
        my_val = 1 if is_black else -1
        opp_val = -my_val

        std_legal = board.get_valid_moves()

        # New-square legality + which rule (length) fires for each.
        new_legal = set()
        new_firing = {}
        for rule in new_rules:
            target = rule['target']
            if target >= 64:
                if new_state[target - 64] != 0:
                    continue
            elif flat[target] != 0:
                continue

            opp_ok = True
            for opp_cell in rule['opponents']:
                val = new_state[opp_cell - 64] if opp_cell >= 64 else flat[opp_cell]
                if val != opp_val:
                    opp_ok = False
                    break
            if not opp_ok:
                continue

            term_cell = rule['terminal']
            term_val = new_state[term_cell - 64] if term_cell >= 64 else flat[term_cell]
            if term_val != my_val:
                continue

            new_legal.add(target)
            L = rule_length(rule)
            if target not in new_firing or L < new_firing[target]:
                new_firing[target] = L

        all_legal = list(std_legal) + list(new_legal)

        if not all_legal:
            empty_std = [c for c in np.where(flat == 0)[0] if c not in CENTER_CELLS]
            empty_new = [64 + j for j in range(N_NEW) if new_state[j] == 0]
            all_empty = empty_std + empty_new
            if not all_empty:
                break
            board_pos = int(rng.choice(all_empty))
        else:
            if save_legal:
                turn_records.append({
                    'prefix_len': len(moves),
                    'all_legal': [int(m) for m in all_legal],
                    'new_firing': {int(k): int(v) for k, v in new_firing.items()},
                })
            board_pos = int(rng.choice(all_legal))

        # Execute the move.
        if board_pos >= 64:
            new_state[board_pos - 64] = my_val
            board.next_hand_color *= -1
        else:
            if board.tentative_move(board_pos) != 0:
                board.update([board_pos])
            else:
                r, c = board_pos // 8, board_pos % 8
                board.state[r, c] = my_val
                board.next_hand_color *= -1

        moves.append(board_pos)
        if len(moves) >= 68:
            break

    return (moves, turn_records) if save_legal else moves


# ============================================================================
# Control 1: balanced training-game generation
# ============================================================================

def generate_balanced_games(new_rules, legal_budget, rng, min_len=5,
                             max_games=None):
    """Generate games until `legal_budget` positions have >=1 new square legal.

    Both conditions call this with the SAME legal_budget, so each sees an equal
    number of new-square training instances (Control 1).  Returns games and
    their per-decision turn_records.
    """
    new_set = set(NEW_SQUARE_IDS)
    games, records = [], []
    n_new_legal = 0
    i = 0
    t0 = time.time()
    while n_new_legal < legal_budget:
        moves, turn_records = generate_game_with_new_squares(
            new_rules, rng, save_legal=True)
        i += 1
        if len(moves) < min_len:
            continue
        games.append(moves)
        records.append(turn_records)
        for tr in turn_records:
            if any(m in new_set for m in tr['all_legal']):
                n_new_legal += 1
        if i % 10000 == 0:
            print(f"  {i} games, {n_new_legal}/{legal_budget} new-square-legal "
                  f"positions ({time.time()-t0:.0f}s)", flush=True)
        if max_games is not None and i >= max_games:
            print(f"  hit max_games={max_games} before budget "
                  f"({n_new_legal}/{legal_budget})", flush=True)
            break
    return games, records, {'n_games': len(games),
                            'n_new_legal_positions': n_new_legal,
                            'n_games_attempted': i}


# ============================================================================
# Controls 2 + 3: matched test manifest (bucket by firing_length, n_legal)
# ============================================================================

def build_test_manifest(games, records, n_positions=5000, min_turn=4):
    """One test position per game (independence), tagged for matched eval.

    IL: a new square is legal -> record target new cells, all_legal, n_legal,
        firing_length (min over legal new squares), and bucket=(len, n_legal).
    LL: standard moves legal -> retention check.
    """
    new_set = set(NEW_SQUARE_IDS)
    test_IL, test_LL = [], []
    used_IL, used_LL = set(), set()

    for gi, (game, turn_records) in enumerate(zip(games, records)):
        if len(test_IL) >= n_positions and len(test_LL) >= n_positions:
            break
        for tr in turn_records:
            if tr['prefix_len'] < min_turn:
                continue
            all_legal = tr['all_legal']
            new_legal = [m for m in all_legal if m in new_set]
            std_legal = [m for m in all_legal if m not in new_set]
            prefix = game[:tr['prefix_len']]

            if new_legal and len(test_IL) < n_positions and gi not in used_IL:
                firing_len = min(tr['new_firing'][m] for m in new_legal)
                test_IL.append({
                    'game_prefix': list(prefix),
                    'target_cells': new_legal,
                    'all_legal': all_legal,
                    'move_idx': tr['prefix_len'],
                    'n_legal': len(all_legal),
                    'n_legal_new': len(new_legal),
                    'firing_length': int(firing_len),
                    'bucket': [int(firing_len), len(all_legal)],
                })
                used_IL.add(gi)

            if std_legal and len(test_LL) < n_positions and gi not in used_LL:
                test_LL.append({
                    'game_prefix': list(prefix),
                    'target_cells': std_legal,
                    'all_legal': all_legal,
                    'move_idx': tr['prefix_len'],
                    'n_legal': len(all_legal),
                })
                used_LL.add(gi)
    return {'IL': test_IL, 'LL': test_LL}


# ============================================================================
# Model-agnostic evaluation of a test manifest
# ============================================================================

def score_manifest(score_fn, manifest, per_bucket=True):
    """Evaluate any model on the shared manifest.

    score_fn(prefix_moves) -> np.ndarray shape (N_CELLS,): a per-cell score in
    [0, 1].  For GPT that's the softmax next-move probability mapped to cells;
    for the MLP it's the per-cell legality sigmoid.  Kept model-agnostic so the
    SAME eval serves both.

    Returns overall IL/LL prob+acc, and (per_bucket) the same broken out by the
    (firing_length, n_legal) bucket so coherent vs incoherent can be compared
    like-for-like (Controls 2 + 3).
    """
    out = {}
    buckets = {}
    for set_name in ('IL', 'LL'):
        positions = manifest.get(set_name, [])
        tot_prob = tot_acc = 0.0
        n = 0
        for pos in positions:
            prefix = pos['game_prefix']
            targets = pos['target_cells']
            if len(prefix) < 1:
                continue
            scores = score_fn(prefix)                 # (N_CELLS,)
            prob = float(sum(scores[c] for c in targets if 0 <= c < N_CELLS))
            acc = 1.0 if int(np.argmax(scores)) in set(targets) else 0.0
            tot_prob += prob
            tot_acc += acc
            n += 1
            if per_bucket and set_name == 'IL' and 'bucket' in pos:
                key = tuple(pos['bucket'])
                b = buckets.setdefault(key, {'prob': 0.0, 'acc': 0.0, 'n': 0})
                b['prob'] += prob
                b['acc'] += acc
                b['n'] += 1
        out[f'{set_name}_prob'] = tot_prob / max(n, 1)
        out[f'{set_name}_acc'] = tot_acc / max(n, 1)
        out[f'{set_name}_n'] = n
    if per_bucket:
        out['IL_buckets'] = {
            f'{L}_{nl}': {'prob': b['prob'] / b['n'],
                          'acc': b['acc'] / b['n'], 'n': b['n']}
            for (L, nl), b in sorted(buckets.items())}
    return out


# ============================================================================
# Generation entry point (writes the shared files for one condition)
# ============================================================================

def condition_dir(output_dir, condition_id):
    return os.path.join(output_dir, f'cond_{condition_id:03d}')


def generate_condition(condition_id, output_dir, legal_budget, seed,
                       n_test_positions=5000, max_games=None, overwrite=False):
    """Generate rules + balanced games + test manifest for one condition."""
    rng = np.random.RandomState(seed)
    cond_name = CONDITIONS[condition_id]
    cdir = condition_dir(output_dir, condition_id)
    os.makedirs(cdir, exist_ok=True)

    games_path = os.path.join(cdir, 'train_games.pickle')
    records_path = os.path.join(cdir, 'train_records.pickle')
    manifest_path = os.path.join(cdir, 'test_manifest.json')
    rules_path = os.path.join(cdir, 'rules.json')
    stats_path = os.path.join(cdir, 'gen_stats.json')

    if os.path.exists(games_path) and not overwrite:
        print(f"[data] cond {condition_id} ({cond_name}) already generated at "
              f"{cdir}; use overwrite=True to regenerate", flush=True)
        with open(games_path, 'rb') as f:
            games = pickle.load(f)
        with open(manifest_path) as f:
            manifest = json.load(f)
        return games, manifest

    print(f"[data] cond {condition_id} ({cond_name}): building rules...", flush=True)
    new_rules = make_rules(cond_name, rng)
    lengths = [rule_length(r) for r in new_rules]
    print(f"  {len(new_rules)} rules, lengths min={min(lengths)} "
          f"max={max(lengths)} mean={np.mean(lengths):.2f}", flush=True)

    print(f"[data] generating games to a budget of {legal_budget} "
          f"new-square-legal positions (Control 1)...", flush=True)
    games, records, gen_stats = generate_balanced_games(
        new_rules, legal_budget, rng, max_games=max_games)
    print(f"  {gen_stats['n_games']} games "
          f"({gen_stats['n_new_legal_positions']} new-square-legal positions)",
          flush=True)

    print(f"[data] building matched test manifest "
          f"(bucket by firing_length x n_legal; Controls 2+3)...", flush=True)
    manifest = build_test_manifest(games, records, n_positions=n_test_positions)
    print(f"  IL={len(manifest['IL'])}  LL={len(manifest['LL'])}", flush=True)

    with open(games_path, 'wb') as f:
        pickle.dump(games, f)
    with open(records_path, 'wb') as f:
        pickle.dump(records, f)
    with open(manifest_path, 'w') as f:
        json.dump(manifest, f)
    with open(rules_path, 'w') as f:
        json.dump([{'target': int(r['target']),
                    'opponents': [int(o) for o in r['opponents']],
                    'terminal': int(r['terminal']),
                    'direction': r['direction'],
                    'length': rule_length(r)} for r in new_rules], f, indent=2)
    with open(stats_path, 'w') as f:
        json.dump({'condition_id': condition_id, 'condition_name': cond_name,
                   'legal_budget': legal_budget, 'seed': seed, **gen_stats,
                   'n_IL': len(manifest['IL']), 'n_LL': len(manifest['LL'])},
                  f, indent=2)
    print(f"[data] wrote {cdir}", flush=True)
    return games, manifest


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--condition-id', type=int, required=True,
                    choices=[0, 1, 2, 3],
                    help='0=coherent, 1=incoherent, 2=coherent_all, '
                         '3=incoherent_all')
    ap.add_argument('--output-dir', default='experiments/new_squares')
    ap.add_argument('--new-square-legal-budget', type=int, default=300000,
                    help='Control 1: positions with >=1 new square legal, '
                         'matched across conditions.')
    ap.add_argument('--n-test-positions', type=int, default=5000)
    ap.add_argument('--max-games', type=int, default=None,
                    help='Safety cap on games attempted before the budget.')
    ap.add_argument('--seed', type=int, default=42)
    ap.add_argument('--overwrite', action='store_true')
    args = ap.parse_args()
    generate_condition(args.condition_id, args.output_dir,
                       args.new_square_legal_budget, args.seed,
                       n_test_positions=args.n_test_positions,
                       max_games=args.max_games, overwrite=args.overwrite)


if __name__ == '__main__':
    main()
