"""Legal-move readout on a FROZEN board-state GPT trunk.

The head is Othello-GPT's head -- Linear(n_embd, 61, bias=False) over
ln_f(trunk) -- trained on next-move cross-entropy, so the output is a
distribution over the 60 playable squares and every legality metric used for
Othello-GPT applies unchanged.

Why next-move prediction is the right objective here: the synthetic games are
generated by random.choice(legal) (data/othello.py:184), so the Bayes-optimal
next-move distribution IS uniform over the legal set.  Training the head to
predict the next move therefore drives it toward exactly the legal set, and
illegal probability mass is a direct measure of how well legality is linearly
readable from the trunk's representation.

The trunk is frozen AND kept in eval() throughout: it carries dropout 0.1 in
three places, and leaving it in train mode would inject noise into the very
features the readout is meant to measure.

    python train_legal_readout.py --ckpt ckpts/board_gpt_L6_20M.ckpt \
        --n-games 2000000 --epochs 3 --cache /root/board_cache/b
"""
import argparse, contextlib, glob, os, pickle, sys, time
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mingpt.model import GPTConfig
from data.othello import OthelloBoardState
from train_board_state_gpt import (GPTBoardState, GPTBoardGrid, BLOCK,
                                   CELL_TO_TOK, _autocast)

TOK_TO_CELL = {t: c for c, t in CELL_TO_TOK.items()}


CENTER = {27, 28, 35, 36}
VALID60 = [c for c in range(64) if c not in CENTER]


def _pad61(logits60):
    """-> (..., 61) with a hard-negative pad logit at index 0, so score_legality
    and the training loss (ignore_index=0) work on every readout alike."""
    pad = torch.full_like(logits60[..., :1], -1e4)
    return torch.cat([pad, logits60], -1)


class LinearHead(nn.Module):
    """Othello-GPT's head: one 512x61 matrix, nothing else."""

    def __init__(self, d, **kw):
        super().__init__()
        self.lin = nn.Linear(d, 61, bias=False)
        nn.init.normal_(self.lin.weight, 0.0, 0.02)

    def forward(self, h, trunk=None):
        return self.lin(h)


class MLPHead(nn.Module):
    def __init__(self, d, hidden=2048, layers=1, **kw):
        super().__init__()
        mods, i = [], d
        for _ in range(layers):
            mods += [nn.Linear(i, hidden), nn.ReLU()]; i = hidden
        mods += [nn.Linear(i, 60)]
        self.net = nn.Sequential(*mods)

    def forward(self, h, trunk=None):
        return _pad61(self.net(h))


class AttnHead(nn.Module):
    """Square-attention over 64 tokens projected out of h.

    The ladder's winner on the true board: 0.048% illegal mass at 399k params,
    beating a 4.7M MLP.  Here the 64 tokens come from a learned projection of
    the trunk's 512-d state rather than from the board itself.
    """

    def __init__(self, d, dm=128, layers=2, heads=4, from_board=False, **kw):
        super().__init__()
        self.dm = dm; self.from_board = from_board
        if from_board:
            self.inp = nn.Linear(3, dm)          # the frozen head's 3 class logits
        else:
            self.inp = nn.Linear(d, 64 * dm)
        self.row = nn.Embedding(8, dm); self.col = nn.Embedding(8, dm)
        enc = nn.TransformerEncoderLayer(dm, heads, 4 * dm, dropout=0.0,
                                         batch_first=True, norm_first=True)
        self.tr = nn.TransformerEncoder(enc, layers)
        self.out = nn.Linear(dm, 1)
        self.register_buffer('rid', torch.arange(64) // 8)
        self.register_buffer('cid', torch.arange(64) % 8)
        self.register_buffer('valid', torch.tensor(VALID60))

    def forward(self, h, trunk=None):
        lead = h.shape[:-1]
        if self.from_board:
            with torch.no_grad():                # frozen board head
                b3 = trunk.head(h).view(*lead, 64, 3).float()
            tok = self.inp(b3)
        else:
            tok = self.inp(h).view(*lead, 64, self.dm)
        tok = tok + self.row(self.rid) + self.col(self.cid)
        tok = self.tr(tok.reshape(-1, 64, self.dm)).view(*lead, 64, self.dm)
        return _pad61(self.out(tok).squeeze(-1)[..., self.valid])


def build_head(kind, d):
    if kind == 'linear':    return LinearHead(d)
    if kind == 'mlp':       return MLPHead(d, 2048, 1)
    if kind == 'mlp2':      return MLPHead(d, 2048, 2)
    if kind == 'attn':      return AttnHead(d, 128, 2, 4, from_board=False)
    if kind == 'attnboard': return AttnHead(d, 128, 2, 4, from_board=True)
    raise ValueError(kind)


class LegalReadout(nn.Module):
    """Frozen trunk + Othello-GPT's head.  Only `head` has gradients."""

    def __init__(self, trunk, n_embd, kind='linear'):
        super().__init__()
        self.trunk = trunk
        self.readout = build_head(kind, n_embd)
        for p in self.trunk.parameters():
            p.requires_grad = False
        self.trunk.eval()

    def train(self, mode=True):
        super().train(mode)
        self.trunk.eval()          # never let the frozen trunk re-enable dropout
        return self

    def features(self, idx):
        tr = self.trunk
        with torch.no_grad():
            x = tr.drop(tr.tok_emb(idx) + tr.pos_emb[:, :idx.size(1), :])
            return tr.ln_f(tr.blocks(x))

    def forward(self, idx, pos=None):
        h = self.features(idx)
        if pos is not None:                      # train on a subset of positions
            h = torch.gather(h, 1, pos.unsqueeze(-1).expand(-1, -1, h.size(-1)))
        return self.readout(h, self.trunk)


def load_trunk(ckpt_path, dev):
    ck = torch.load(ckpt_path, map_location='cpu')
    cfg = GPTConfig(**{k: v for k, v in ck['cfg'].items()})
    head = ck.get('args', {}).get('head', 'flat')
    trunk = (GPTBoardGrid(cfg, rank=ck['args'].get('head_rank', 64))
             if head == 'grid' else GPTBoardState(cfg))
    trunk.load_state_dict(ck['model'])
    print(f'loaded {ckpt_path}: {cfg.n_layer}L d{cfg.n_embd} head={head}', flush=True)
    return trunk.to(dev), cfg


def held_out_games(data_dir, n_games, n_held=3, min_len=60):
    """The LAST n_held pickles.  ogpt_topk_legality.load_games takes the FIRST
    files, which are inside this trunk's 204-file training set."""
    files = sorted(glob.glob(os.path.join(data_dir, '*.pickle')))[-n_held:]
    out = []
    for f in files:
        with open(f, 'rb') as fh:
            for g in pickle.load(fh):
                if len(g) >= min_len:
                    out.append(g)
                    if len(out) >= n_games:
                        return out
    return out


@torch.no_grad()
def score_legality(model, games, dev, ply_min, ply_max, ks, amp, batch=64):
    """Top-K FRAC capped at min(k, n_legal), plus illegal probability mass."""
    model.eval()
    hit = {k: 0 for k in ks}; frac = {k: 0.0 for k in ks}
    n = 0; pos_mass = []; game_max = []
    t0 = time.time()
    for b0 in range(0, len(games), batch):
        bt = games[b0:b0 + batch]
        toks = torch.tensor([[CELL_TO_TOK[c] for c in g[:ply_max]] for g in bt],
                            dtype=torch.long, device=dev)
        with _autocast(dev, amp):
            logits = model(toks).float()                 # (B, T, 61)
        for bi, g in enumerate(bt):
            bd = OthelloBoardState(); gmax = 0.0
            for ply in range(ply_max):
                if ply >= ply_min:
                    legal = set(bd.get_valid_moves())
                    if legal:
                        sc = logits[bi, ply - 1, 1:]     # logit 0 is the pad token
                        order = torch.argsort(sc, descending=True)
                        for k in ks:
                            ke = min(k, len(legal))
                            top = [TOK_TO_CELL[int(order[j]) + 1] for j in range(ke)]
                            h = sum(c in legal for c in top)
                            hit[k] += int(h == ke); frac[k] += h / ke
                        p = torch.softmax(sc, -1)
                        ill = float(sum(p[CELL_TO_TOK[c] - 1]
                                        for c in TOK_TO_CELL.values()
                                        if c not in legal))
                        pos_mass.append(ill); gmax = max(gmax, ill)
                        n += 1
                bd.update([g[ply]])
            game_max.append(gmax)
        if (b0 // batch) % 10 == 0:
            print(f'  scored {b0 + len(bt)}/{len(games)} games '
                  f'({time.time() - t0:.0f}s)', flush=True)
    pm = np.array(pos_mass); gm = np.array(game_max)
    return dict(n=n, hit={k: hit[k] / max(n, 1) for k in ks},
                frac={k: frac[k] / max(n, 1) for k in ks},
                med_mass=float(np.median(pm)), mean_mass=float(pm.mean()),
                gmax_med=float(np.median(gm)),
                gt5=float((gm > .05).mean()), gt10=float((gm > .10).mean()))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--ckpt', default='ckpts/board_gpt_L6_20M.ckpt')
    ap.add_argument('--data-dir', default='./data/othello_synthetic')
    ap.add_argument('--cache', default='./cache/board')
    ap.add_argument('--n-games', type=int, default=2_000_000)
    ap.add_argument('--cache-games', type=int, default=0,
                    help="the cache's game count, if using a slice of a bigger "
                         "cache (0 = same as --n-games)")
    ap.add_argument('--epochs', type=int, default=3)
    ap.add_argument('--batch-size', type=int, default=1024)
    ap.add_argument('--lr', type=float, default=1e-3)
    ap.add_argument('--eval-games', type=int, default=2000)
    ap.add_argument('--ply-min', type=int, default=5)
    ap.add_argument('--ply-max', type=int, default=54)   # half-open: moves 5-53
    ap.add_argument('--ks', type=int, nargs='+', default=[1, 3, 5])
    ap.add_argument('--readout', default='linear',
                    choices=['linear', 'mlp', 'mlp2', 'attn', 'attnboard'])
    ap.add_argument('--pos-sample', type=int, default=0,
                    help='train on this many random positions per game (0 = all). '
                         'The trunk runs over the full prefix either way; this '
                         'only bounds the head, which matters for attn.')
    ap.add_argument('--fp32', action='store_true')
    ap.add_argument('--out', default='ckpts/legal_readout.ckpt')
    a = ap.parse_args()

    dev = 'cuda' if torch.cuda.is_available() else 'cpu'
    amp = not a.fp32
    if dev == 'cuda':
        torch.backends.cuda.matmul.allow_tf32 = True
        torch.backends.cudnn.allow_tf32 = True
    print(f'device {dev}  precision {"bf16" if amp and dev == "cuda" else "fp32"}',
          flush=True)

    trunk, cfg = load_trunk(a.ckpt, dev)
    model = LegalReadout(trunk, cfg.n_embd, a.readout).to(dev)
    tp = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f'{tp:,} trainable (head only) of '
          f'{sum(p.numel() for p in model.parameters()):,}', flush=True)

    # Reuse the board-state cache: only X (move tokens) is needed, since the
    # next-move target is X shifted by one.  Token 0 is pad, so ignore_index=0
    # drops both padded targets and the positions past a game's end.
    xp = f'{a.cache}_tr{a.cache_games or a.n_games}_X.npy'
    if not os.path.exists(xp):
        sys.exit(f'no token cache at {xp} -- run train_board_state_gpt.py '
                 f'with --n-games {a.cache_games or a.n_games} '
                 f'--cache {a.cache} first')
    X = np.load(xp, mmap_mode='r')[:a.n_games]
    print(f'{len(X):,} training games from {xp}', flush=True)

    opt = torch.optim.AdamW([p for p in model.parameters() if p.requires_grad],
                            lr=a.lr, weight_decay=0.0)
    spe = (len(X) + a.batch_size - 1) // a.batch_size
    sched = torch.optim.lr_scheduler.OneCycleLR(opt, max_lr=a.lr,
                                                total_steps=a.epochs * spe,
                                                pct_start=0.05)
    t0 = time.time(); step = 0
    for ep in range(a.epochs):
        perm = np.random.permutation(len(X))
        for i in range(0, len(X), a.batch_size):
            idx = np.sort(perm[i:i + a.batch_size])
            x = torch.from_numpy(np.asarray(X[idx])).long().to(dev)
            with _autocast(dev, amp):
                if a.pos_sample:
                    # positions 0..BLOCK-2 only: the target is the NEXT token
                    pos = torch.randint(0, x.size(1) - 1, (x.size(0), a.pos_sample),
                                        device=dev)
                    lg = model(x, pos)
                    tgt = torch.gather(x, 1, pos + 1)
                    loss = F.cross_entropy(lg.reshape(-1, lg.size(-1)),
                                           tgt.reshape(-1), ignore_index=0)
                else:
                    lg = model(x)
                    loss = F.cross_entropy(lg[:, :-1].reshape(-1, lg.size(-1)),
                                           x[:, 1:].reshape(-1), ignore_index=0)
            opt.zero_grad(set_to_none=True); loss.backward()
            opt.step(); sched.step(); step += 1
            if step % 250 == 0:
                print(f'  ep{ep} step {step}/{a.epochs*spe}  loss {loss.item():.4f}  '
                      f'({time.time()-t0:.0f}s)', flush=True)
        print(f'epoch {ep} done ({time.time()-t0:.0f}s)', flush=True)

    os.makedirs(os.path.dirname(a.out) or '.', exist_ok=True)
    torch.save({'head': model.readout.state_dict(), 'args': vars(a)}, a.out)
    print(f'saved {a.out}', flush=True)

    games = held_out_games(a.data_dir, a.eval_games)
    print(f'\nscoring {len(games)} HELD-OUT games, plies '
          f'[{a.ply_min},{a.ply_max}) = moves {a.ply_min}-{a.ply_max-1}', flush=True)
    r = score_legality(model, games, dev, a.ply_min, a.ply_max, a.ks, amp)
    print(f'\n=== readout "{a.readout}" on frozen board-state trunk, N={r["n"]:,} ===')
    for k in a.ks:
        print(f'  top-{k}:  FRAC {100*r["frac"][k]:6.2f}%   ALL {100*r["hit"][k]:6.2f}%')
    print(f'  illegal mass: median {100*r["med_mass"]:.3f}%  '
          f'mean {100*r["mean_mass"]:.3f}%')
    print(f'  per-game max illegal mass: median {100*r["gmax_med"]:.2f}%  '
          f'>5% {100*r["gt5"]:.1f}%  >10% {100*r["gt10"]:.1f}%')
    print('\n  references (moves 5-53): Othello-GPT linear head 99.95 / 0.25%; '
          'TRUE board -- linear 98.98 / 26.00%, mlp2 99.81 / 0.199%, '
          'attn 99.85 / 0.048%')


if __name__ == '__main__':
    main()
